// src/app/demo-walkthrough/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
// Removed: import Image from 'next/image';
import { Compass, FileText, Lightbulb, Zap, Route, MessageCircle, LogIn, ArrowLeft } from 'lucide-react';
import { ThemeToggleButton } from '@/components/core/ThemeToggleButton';

export default function DemoWalkthroughPage() {
  const [currentYear, setCurrentYear] = useState<string | null>(null);

  useEffect(() => {
    setCurrentYear(new Date().getFullYear().toString());
  }, []);

  const steps = [
    {
      icon: LogIn,
      title: 'Step 1: Login or Sign Up',
      description: 'Start by logging into your Career Compass account. If you\'re new, a simple sign-up process (using any email for this demo) gets you started.',
    },
    {
      icon: FileText,
      title: 'Step 2: Upload & Analyze Your Resume',
      description: 'Navigate to the "Resume" section. Upload your resume (PDF, DOCX, or image formats). Our AI will extract the text and provide a detailed analysis, including an overall score, feedback on clarity, impact, format, ATS friendliness, positive points, and areas for improvement.',
    },
    {
      icon: Lightbulb,
      title: 'Step 3: Take the Personality Quiz',
      description: 'Go to the "Quiz" section. Answer a series of questions designed to understand your work style, strengths, and preferences. This helps refine the AI\'s career suggestions.',
    },
    {
      icon: Zap,
      title: 'Step 4: View AI-Powered Results - Suggestions',
      description: 'Once your resume is analyzed and the quiz is completed, head to the "Results" page. Here, you\'ll find personalized career suggestions generated by our AI, along with the reasoning behind them.',
    },
    {
      icon: Route,
      title: 'Step 5: Explore Detailed Career Roadmaps',
      description: 'For each career suggestion, explore a detailed, structured roadmap. This includes skills to develop, key milestones, learning resources, networking tips, timeline estimates, and an actionable next step.',
    },
    {
      icon: MessageCircle,
      title: 'Step 6: Interact with the AI Career Help Chatbot',
      description: 'Also on the "Results" page, use the AI chatbot to ask follow-up questions about your analysis, suggestions, roadmaps, or any other career-related queries. The chatbot uses your data for contextual advice.',
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-secondary flex flex-col items-center">
      <header className="w-full container mx-auto py-6 px-4 flex justify-between items-center">
        <Link href="/" className="flex items-center space-x-2">
          <Compass className="h-10 w-10 text-primary" />
          <span className="font-headline text-3xl font-bold text-primary">Career Compass</span>
        </Link>
        <ThemeToggleButton />
      </header>

      <main className="container mx-auto px-4 py-8 flex-grow">
        <Card className="shadow-xl mb-8">
          <CardHeader className="text-center">
            <CardTitle className="text-4xl font-headline text-primary">How Career Compass Works</CardTitle>
            <CardDescription className="text-lg text-foreground/80">
              A step-by-step guide to navigating your career path with AI.
            </CardDescription>
          </CardHeader>
          {/* Removed image section */}
        </Card>

        <div className="space-y-6">
          {steps.map((step, index) => (
            <Card key={index} className="shadow-lg hover:shadow-xl transition-shadow duration-300">
              <CardHeader>
                <div className="flex items-start space-x-4">
                  <div className="flex-shrink-0 bg-primary/10 p-3 rounded-full mt-1">
                    <step.icon className="h-7 w-7 text-primary" />
                  </div>
                  <div>
                    <CardTitle className="text-2xl font-semibold">{step.title}</CardTitle>
                    <CardDescription className="text-base text-foreground/90 mt-1">{step.description}</CardDescription>
                  </div>
                </div>
              </CardHeader>
            </Card>
          ))}
        </div>

        <div className="mt-12 text-center">
          <Button asChild size="lg">
            <Link href="/">
              <ArrowLeft className="mr-2 h-5 w-5" /> Back to Home
            </Link>
          </Button>
        </div>
      </main>

      <footer className="w-full py-8 text-center text-sm text-foreground/70">
        <p>&copy; {currentYear ? currentYear : '...'} Career Compass. All rights reserved.</p>
      </footer>
    </div>
  );
}
